version: '3.8'

services:
  neo4j:
    image: neo4j:latest
    container_name: neo4j-bench
    environment:
      - NEO4J_AUTH=${NEO4J_USER}/${NEO4J_PASSWORD}  # Correct format (neo4j/password)
    ports:
      - "7474:7474"   # HTTP Web UI
      - "7687:7687"   # Bolt protocol for clients
