services:
  db:
    image: gvenzl/oracle-xe
    container_name: oracle
    ports:
      - "1521:1521"
    environment:
      ORACLE_PASSWORD: ${ORACLE_PASSWORD}
    volumes:
      - oracle-data:/opt/oracle/oradata

  seed:
    build: ./init
    depends_on:
      - db
    environment:
      DB_HOST: db:1521/XEPDB1
      DB_USER: ${ORACLE_USER}
      DB_PASS: ${ORACLE_PASSWORD}
    entrypoint: [ "python", "populate.py" ]

volumes:
  oracle-data: