CREATE TABLE researcher (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP NOT NULL DEFAULT now(),
  name VARCHAR2(255) NOT NULL
);

CREATE TABLE paper (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP NOT NULL DEFAULT now(),
  title VARCHAR2(255) NOT NULL
);

CREATE TABLE topic (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP NOT NULL DEFAULT now(),
  name VARCHAR2(255) NOT NULL
);

CREATE TABLE conference (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP NOT NULL DEFAULT now(),
  name VARCHAR2(255) NOT NULL,
  year NUMBER
);

CREATE TABLE organization (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP NOT NULL DEFAULT now(),
  name VARCHAR2(255) NOT NULL
);

CREATE TABLE researcher_paper (
  researcher_id NUMBER REFERENCES researcher(id),
  paper_id NUMBER REFERENCES paper(id),
  PRIMARY KEY (researcher_id, paper_id)
);

CREATE TABLE paper_topic (
  paper_id NUMBER REFERENCES paper(id),
  topic_id NUMBER REFERENCES topic(id),
  PRIMARY KEY (paper_id, topic_id)
);

CREATE TABLE topic_conference (
  topic_id NUMBER REFERENCES topic(id),
  conference_id NUMBER REFERENCES conference(id),
  PRIMARY KEY (topic_id, conference_id)
);

CREATE TABLE conference_org (
  conference_id NUMBER REFERENCES conference(id),
  org_id NUMBER REFERENCES organization(id),
  PRIMARY KEY (conference_id, org_id)
);
