services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "frosthand_mssql_password123*!"
    ports:
      - "1433:1433"
    healthcheck:
      test: ["CMD", "/opt/mssql-tools/bin/sqlcmd", "-S", "localhost", "-U", "sa", "-P", "frosthand_mssql_password123*!", "-Q", "SELECT 1"]
      interval: 10s
      timeout: 5s
      retries: 10

  seed:
    build: ./init
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: sa
      DB_PASS: frosthand_mssql_password123*!
    entrypoint: [ "python", "populate.py" ]

volumes:
  db-data: