services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: ${MSSQL_PASSWORD}
    ports:
      - "1433:1433"
    healthcheck:
      test: ["CMD", "/opt/mssql-tools/bin/sqlcmd", "-S", "localhost", "-U", "${MSSQL_USER}", "-P", "${MSSQL_PASSWORD}", "-Q", "SELECT 1"]
      interval: 10s
      timeout: 5s
      retries: 10

  seed:
    build: ./init
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: ${MSSQL_USER}
      DB_PASS: ${MSSQL_PASSWORD}
    entrypoint: [ "python", "populate.py" ]

volumes:
  db-data: