version: '3.8'

services:
  db:
    image: mariadb:11.1
    environment:
      MARIADB_ROOT_PASSWORD: rootpass
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
      MARIADB_DATABASE: frosthand_mariadb
    ports:
      - "33306:3306"

  seed:
    build: ./init
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: ${MARIADB_USER}
      DB_PASS: ${MARIADB_PASSWORD}
    entrypoint: [ "python", "populate.py" ]

volumes:
  mariadb_data:
