services:
  db:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: frosthand_mysql_rootpass
      MYSQL_DATABASE: frosthand_mysql_db
      MYSQL_USER: frosthand_mysql_username
      MYSQL_PASSWORD: frosthand_mysql_password
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql


volumes:
  mysql-data: