version: '3.9'
services:
  db:
    image: cockroachdb/cockroach:v23.1.11
    container_name: cockroach
    command: start-single-node --insecure
    ports:
      - "26257:26257"   # SQL port
      - "8080:8080"     # Admin UI
    volumes:
      - cockroach-data:/cockroach/cockroach-data

  seed:
    build: ./init
    depends_on:
      - db
    environment:
      DB_HOST: db
    entrypoint: [ "python", "populate.py" ]

volumes:
  cockroach-data: