version: '3.8'
services:
  redis:
    image: redis:7
    ports:
      - "6379:6379"
    command: [ "redis-server", "--requirepass", "${REDIS_PASSWORD}" ]
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}  # Optional but useful for consistency

  seed:
    build: ./init
    depends_on:
      - redis
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
